### ISSUE TITLE
Call For Help

### ISSUE THREAD

**Issue by hplegend** [PRBonn/spatio-temporal-mapping#2]
as mentioned in README "Mapping (generate a map from a sequence of RGBD images by computing the odometry or with given poses)" , I want to know that if I input a RGBD images without pose infomation, the code can calculate the odomenty and then mapping like a slam system? or I must have to input a image sequnce and pose?

**Comment by l00p3** [comment]
By default the system runs a visual-odometry algorithm to compute the pose for each incoming frame. You can also set an option, as explained in the README, to give pre-computed poses: in this case only mapping will be executed. 
I want to underline the fact that, even if my system computes poses while producing a 3D representation of the environment (mapping) cannot be considered a SLAM system, because no global consistency is ensured (no loop closure, no pose graph optimization and so on).
